package edu.cuny.csi.csc330.bankatm;

//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;

/**
 * @author  Administrator
 * @created November 30, 2019
 */
public class NumberDialog extends JDialog
{
    static NumberDialog thetest2;

    JPanel pnPanel0;
    JLabel lbLabel0;
    JTextField tf;
    JButton btButNum1;
    JButton btButNum2;
    JButton btButNum3;
    JButton btButNum4;
    JButton btButNum5;
    JButton btButNum6;
    JButton btButNum7;
    JButton btButNum8;
    JButton btButNum9;
    JButton btButNum0;
    JButton btButNumEnter;
    JButton btButNumDel;

    /**
     */
    public static void main( String args[] )
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch ( ClassNotFoundException e )
        {
        }
        catch ( InstantiationException e )
        {
        }
        catch ( IllegalAccessException e )
        {
        }
        catch ( UnsupportedLookAndFeelException e )
        {
        }
        String val = NumberDialog.showDialog("Account Number", "Enter your Account Number");
        System.out.println("Number entered in dialog: " + val);
    }

    /**
     */
    private NumberDialog(String title, String text)
    {
        super();
        //super( OWNER, "TITLE", MODAL );

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setTitle(title);

        pnPanel0 = new JPanel();
        GridBagLayout gbPanel0 = new GridBagLayout();
        GridBagConstraints gbcPanel0 = new GridBagConstraints();
        pnPanel0.setLayout( gbPanel0 );

        lbLabel0 = new JLabel( text );
        gbcPanel0.gridx = 6;
        gbcPanel0.gridy = 1;
        gbcPanel0.gridwidth = 2;
        gbcPanel0.gridheight = 1;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 1;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( lbLabel0, gbcPanel0 );
        pnPanel0.add( lbLabel0 );

        tf = new JTextField( );
        tf.setEditable(false);
        gbcPanel0.gridx = 2;
        gbcPanel0.gridy = 3;
        gbcPanel0.gridwidth = 8;
        gbcPanel0.gridheight = 1;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( tf, gbcPanel0 );
        pnPanel0.add( tf );

        btButNum1 = new JButton( "1"  );
        gbcPanel0.gridx = 2;
        gbcPanel0.gridy = 6;
        gbcPanel0.gridwidth = 2;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum1, gbcPanel0 );
        pnPanel0.add( btButNum1 );

        btButNum2 = new JButton( "2"  );
        gbcPanel0.gridx = 6;
        gbcPanel0.gridy = 6;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum2, gbcPanel0 );
        pnPanel0.add( btButNum2 );

        btButNum3 = new JButton( "3"  );
        gbcPanel0.gridx = 9;
        gbcPanel0.gridy = 6;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum3, gbcPanel0 );
        pnPanel0.add( btButNum3 );

        btButNum4 = new JButton( "4"  );
        gbcPanel0.gridx = 2;
        gbcPanel0.gridy = 10;
        gbcPanel0.gridwidth = 2;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum4, gbcPanel0 );
        pnPanel0.add( btButNum4 );

        btButNum5 = new JButton( "5"  );
        gbcPanel0.gridx = 6;
        gbcPanel0.gridy = 10;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum5, gbcPanel0 );
        pnPanel0.add( btButNum5 );

        btButNum6 = new JButton( "6"  );
        gbcPanel0.gridx = 9;
        gbcPanel0.gridy = 10;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum6, gbcPanel0 );
        pnPanel0.add( btButNum6 );

        btButNum7 = new JButton( "7"  );
        gbcPanel0.gridx = 2;
        gbcPanel0.gridy = 13;
        gbcPanel0.gridwidth = 2;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum7, gbcPanel0 );
        pnPanel0.add( btButNum7 );

        btButNum8 = new JButton( "8"  );
        gbcPanel0.gridx = 6;
        gbcPanel0.gridy = 13;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum8, gbcPanel0 );
        pnPanel0.add( btButNum8 );

        btButNum9 = new JButton( "9"  );
        gbcPanel0.gridx = 9;
        gbcPanel0.gridy = 13;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum9, gbcPanel0 );
        pnPanel0.add( btButNum9 );

        btButNum0 = new JButton( "0"  );
        gbcPanel0.gridx = 6;
        gbcPanel0.gridy = 16;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 1;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNum0, gbcPanel0 );
        pnPanel0.add( btButNum0 );

        btButNumEnter = new JButton( "Enter"  );
        gbcPanel0.gridx = 9;
        gbcPanel0.gridy = 16;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 1;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNumEnter, gbcPanel0 );
        pnPanel0.add( btButNumEnter );

        btButNumDel = new JButton( "Del"  );
        gbcPanel0.gridx = 2;
        gbcPanel0.gridy = 16;
        gbcPanel0.gridwidth = 2;
        gbcPanel0.gridheight = 1;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints( btButNumDel, gbcPanel0 );
        pnPanel0.add( btButNumDel );

        JButton buttons[] = {
                btButNum0,
                btButNum1, btButNum2, btButNum3,
                btButNum4, btButNum5, btButNum6,
                btButNum7, btButNum8, btButNum9
        };

        for (int i = 0; i < 10; i++) {
            buttons[i].setActionCommand(Integer.toString(i));
            buttons[i].addActionListener(this::onButtonKeyPressed);
        }

        btButNumEnter.addActionListener(this::onButtonEnter);
        btButNumDel.addActionListener(this::onButtonDelete);

        setDefaultCloseOperation( DISPOSE_ON_CLOSE );

        setContentPane( pnPanel0 );
        pack();
        setVisible(true);
    }

    public String getValue() {
        return tf.getText();
    }

    private void onButtonKeyPressed(ActionEvent e) {
        JButton button = (JButton)e.getSource();
        tf.setText(tf.getText() + button.getActionCommand());
    }

    private void onButtonDelete(ActionEvent e) {
        String text = tf.getText();
        if (!text.isEmpty()) {
            tf.setText(text.substring(0, text.length() - 1));
        }
    }

    private void onButtonEnter(ActionEvent e) {
        setVisible(false);
        dispose();
    }

    public static String showDialog(String title, String text) {
        NumberDialog dialog = new NumberDialog(title, text);
        return dialog.getValue();
    }
}
